### ISSUE TITLE
Please update for Plasma 6

### ISSUE THREAD

**Issue by joobert** [emvaized/kde-snap-assist#48] opened 2024-04-29 23:04 UTC
This is a game changer. Please do not let your work go to waste

**Comment by emvaized** [comment] 2024-06-30 23:19
Closing this as duplicate of the [existing issue](https://github.com/emvaized/kde-snap-assist/issues/47). Please subscribe to it instead for any updates

**Closed as not planned by emvaized** 2024-06-30 23:19 UTC
