### ISSUE TITLE
Bug: Titlebar is visible sometimes

### ISSUE THREAD

**Issue by margual56** [emvaized/kde-snap-assist#13] opened 2022-08-11 23:20 UTC
I'm on Wayland (on ArchBTW), and the titlebar is visible sometimes:

![Screenshot](https://user-images.githubusercontent.com/30444886/184257765-5659e721-f3ef-4a99-b19e-c6a70a9cabc4.png)

It seems to only occur when it is selecting some position at the bottom (bottom left or right, or horizontal snapping in the bottom as seen in the screenshot).

That window can be moved around, and if closed the snapping script stops working.

_Note: Did not test on X11_

**Comment by emvaized** [comment] 2022-08-12 18:37
It seems that `X11BypassWindowManagerHint` flag, which sets the window as titlebar-less, does not work reliably on Wayland. 
It can be replaced with `FramelessWindowHint` flag, which solves the problem on Wayland — but breaks the script on X11, as the assist's window becomes invisible.

**Comment by emvaized** [comment] 2022-08-12 23:11
Alright, it turns out you could specify both flags at the same time, and it seems to be working fine in both X11 and Wayland.
Would be great if you could test and confirm it by testing latest version from the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev) ([instructions how to install](https://github.com/emvaized/kde-snap-assist/issues/12#issuecomment-1213457657)).

**Comment by margual56** [comment] 2022-08-12 23:53
> Alright, it turns out you could specify both flags at the same time, and it seems to be working fine in both X11 and Wayland. Would be great if you could test and confirm it by installing the latest version from the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev)).

If I did it correctly, I think the bug is still present:

![2022-08-13_01-50](https://user-images.githubusercontent.com/30444886/184457788-7ce5e097-4ce6-44a9-9ad6-b2864ad5b514.png)

**Comment by emvaized** [comment] 2022-08-13 01:02
Did you re-login to Plasma after install?

**Comment by emvaized** [comment] 2022-08-13 01:03
"Change layout" button's icon should be another in current "dev" version

**Comment by emvaized** [comment] 2022-08-14 13:08
The fix is now included in new version 1.3 and the main branch.

**Comment by emvaized** [comment] 2022-08-14 13:13
Closing this as I no longer can reproduce the issue. Please feel free to reopen if your issue remains.

**Closed by emvaized** 2022-08-14 13:13 UTC

**Comment by margual56** [comment] 2022-08-15 16:28
Can confirm it is fixed, sorry for the bad debugging on my part. 

Nice job! :)
