### ISSUE TITLE
Bug: Snapping does not resize the window

### ISSUE THREAD

**Issue by margual56** [emvaized/kde-snap-assist#14] opened 2022-08-11 23:27 UTC
On Wayland, ArchBTW.

When snapping, the window does not resize horizontally: it retains whatever size it had before. Is that intentional?

_Note: Did not test on X11_

**Comment by emvaized** [comment] 2022-08-12 18:34
I can confirm this — on Wayland some windows get resized normally for me (such as Kate), and some don't (such as Konsole). 
I would cautiously assume that this is a problem with the window manager itself on Wayland — because the script uses the only way possible for a KWin script to resize the window, and on X11 it works just fine.

**Comment by margual56** [comment] 2022-08-12 21:12
Wow! Maybe we could submit the bug to KWin then? ([here](https://bugs.kde.org/enter_bug.cgi?product=kwin&Bugzilla_restrictlogin=on&GoAheadAndLogIn=Log%20in))

**Comment by emvaized** [comment] 2022-08-12 22:22
Sure, let's try it. 
What are your system specs — KDE frameworks version and stuff? As I haven't updated mine for a little while

**Comment by emvaized** [comment] 2022-08-12 22:40
And could you also confirm — does the window width remains unchanged only for specific windows (like Konsole in my case, and Kate resizes fine), or for all windows?

**Comment by margual56** [comment] 2022-08-12 23:41
> And could you also confirm — does the window width remains unchanged only for specific windows (like Konsole in my case, and Kate resizes fine), or for all windows?

In my case this happens for all windows (that I have tried, which are Alacritty, Thunderbird, Firefox, Kate, Settings, Dolphin and vscode)

> Sure, let's try it. What are your system specs — KDE frameworks version and stuff? As I haven't updated mine for a little while
- KDE Plasma Version: 5.25.4
- KDE Framework Version: 5.96.0
- Qt Version: 5.15.5
- Kernel: 4.18.16-zen1-1
- Graphics Platform: Wayland

Thank you!

**Comment by emvaized** [comment] 2022-08-13 02:35
I created a bug report. Let's see how it goes:
https://bugs.kde.org/show_bug.cgi?id=457822

**Comment by emvaized** [comment] 2022-08-16 21:05
I think I'll be closing this for now. 
If you'll find any information confirming that this is not a KWin's bug, but a problem with the script — or a possible workaround, please feel free to reopen.

**Closed by emvaized** 2022-08-16 21:05 UTC

**Comment by semarainc** [comment] 2022-08-17 06:50
sorry for reopening this issue
but i found this script 
Link: https://github.com/qewer33/Exquisite 
(handle window snap like windows 11)
It works on wayland on resizing window, so i guess maybe it is not a KWin's bug but a bug on the script

maybe you can take a look if you don't mind
Thanks

**Comment by emvaized** [comment] 2022-08-17 14:17
It seems that it uses the same `geometry` API, but in a some different way. 
I just implemented the same for test in the [dev branch](https://github.com/emvaized/kde-snap-assist/tree/dev) — would be great if you could check and confirm if it's working.

For this you'd need to:
- Delete current version of script and re-login to KDE Plasma
- Download [the code](https://github.com/emvaized/kde-snap-assist/tree/dev) as .zip (green "Code" button > "Download as ZIP"), and rename file to .kwinscript extension
- Use the "Install from file" button in System settings > Windows manager > KWin scripts
- Re-login to Plasma again (or restart KWin) to make sure the script is installed

**Comment by semarainc** [comment] 2022-08-18 06:43
Hi
Thank you for your hard work
the code from dev branch works well on my laptop but there is a slight issue

when i snap a window from using the script, the script still think the other window need snap assists

here is the video:
[https://youtu.be/_Z29SH4p4Ag](url)

and other issue (if you don't mind)
i think the setting menu is too big for my screen (1366x768), i hope you can make it so it can adapt for small screen resolution
![image](https://user-images.githubusercontent.com/19622207/185313517-882bddc1-bf92-45cc-9d96-880e29890417.png) 

Thank you for your hard work :D

**Comment by emvaized** [comment] 2022-08-18 18:46
@semarainc 
Thanks for your report! 
Would be glad if you could create new separate issue tickets for the problems you mentioned, as they're not related to the topic discussed in this ticket.

**Comment by semarainc** [comment] 2022-08-18 19:19
Thank you again for your hard work
I will make separate topic regarding of setting menu problem
