### ISSUE TITLE
Bug: Causing all keyboard inputs to be swallowed, causing the whole desktop unusable

### ISSUE THREAD

**Issue by sdip15fa** [emvaized/kde-snap-assist#45] opened 2023-12-08 13:13 UTC
Platform: wayland / x11
KDE: 5.27.10
KDE frameworks: 5.112.0
QT: 5.15.11
Linux: 6.6.4-zen1-1-zen
Distro: Arch
Problem: https://bbs.archlinux.org/viewtopic.php?pid=2136003#p2136003
Recently I found my keyboard stops working in KDE and gnome except for a few keys like meta. After debugging for days I have managed to identify the problem to be located at `~/.local/share/kwin/scripts/kdesnapassist/`, and the problem ceased after removing the directory.

**Comment by emvaized** [comment] 2024-02-13 20:52
Duplicate of https://github.com/emvaized/kde-snap-assist/issues/43

**Closed by emvaized** 2024-02-13 20:52 UTC
