### ISSUE TITLE
Unwanted assist reveal on Plasma Wayland

### ISSUE THREAD

**Issue by semarainc** [emvaized/kde-snap-assist#24] opened 2022-08-19 08:03 UTC
Hi
i would like to report an issue regarding snap assists
before that here is my spec:

> Operating System: Manjaro Linux
KDE Plasma Version: 5.24.6
KDE Frameworks Version: 5.96.0
Qt Version: 5.15.5
Kernel Version: 5.17.15-1-MANJARO (64-bit)
Graphics Platform: Wayland

when i snap a window from using the script, the script still think the other window need snap assists

here is the video:
https://youtu.be/_Z29SH4p4Ag

I hope you are willing to look into this issue
Thank you

**Comment by emvaized** [comment] 2022-08-19 11:13
Hi! 
I applied a possible fix for this behavior in the [dev](https://github.com/emvaized/kde-snap-assist/tree/dev) branch. 
Would be glad if you could test and confirm if it's working ([installation guide](https://github.com/emvaized/kde-snap-assist/tree/dev#manual-installation))

**Comment by semarainc** [comment] 2022-08-19 12:15
Hi
thank you for your effort :D

Dev branch fixes unwanted assists reveal on side-by-side tiling/snap
but the problem also occurs when doing quarter tiling/snap
this is the video for illustration
Link : https://youtu.be/4O3yDb78-PI

**Comment by emvaized** [comment] 2022-08-20 21:58
I've gave it another try in the dev branch. Could you test?

**Comment by semarainc** [comment] 2022-08-21 07:09
Hi 
Thank you for your effort again ^_^

for the issue regarding quarter tiling unwanted assists is now fixed after testing the dev branch, side by side tiling is also fine :D 
Here is the video
Link: https://youtu.be/h7uFsXOenFc

maybe about telegram window issue on video, i don't know if that's a bug or not
Thank you again :D

**Comment by emvaized** [comment] 2022-08-21 13:35
Okay, great – then I'll merge the changes to the main branch and publish an update within few days. Thanks for reporting and testing!

The Telegram case you mentioned in the last video seems to be common Wayland behavior, when window has some sort of minimum size set under the hood. I also noticed it happen with the system settings window and system monitor. 
Maybe they'll fix it later, or it may be some Wayland security thing by design – I'm not sure. As you can see, the issue happens with system snap functionality, not the script's one.

**Comment by semarainc** [comment] 2022-08-21 14:35
Ok, thank you for the explanation :D

I think you can close this topic after the dev branch merged with main and published :D

Thanks

**Closed** 2022-08-21 19:50 UTC
